#!/usr/bin/env python
from appscript import app, k
import aem

TEMPLATE = [
	[u'title', u'TITLE_TEXT (optional row)'],
	[u'settings', u'SETTINGS_LIST (optional row)'],
	[u'XLABEL', u'YLABEL (required row)'],
	[u'XUNIT', u'YUNIT (required row)'],
	[u'legend', u'LEGEND_LABEL (optional row)'],
	[u'X', u'Y;main;color=green;marker=s'],
	[1.0, 4.0],
	[2.0, 4.5],
]

app(u'Microsoft Excel').make(at=app.active_workbook, new=k.worksheet)
app(u'Microsoft Excel').AS_newreference(aem.app.elements('X117'))[u'A1:B8'].value.set(TEMPLATE)
